<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProductEntity extends \App\Entities\ProductEntity implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'brand' => [parent::class, 'brand', null],
        "\0".'*'."\0".'description' => [parent::class, 'description', null],
        "\0".'*'."\0".'id' => [parent::class, 'id', null],
        "\0".'*'."\0".'inStock' => [parent::class, 'inStock', null],
        "\0".'*'."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'attributes' => [parent::class, 'attributes', null],
        "\0".parent::class."\0".'category' => [parent::class, 'category', null],
        "\0".parent::class."\0".'gallery' => [parent::class, 'gallery', null],
        "\0".parent::class."\0".'prices' => [parent::class, 'prices', null],
        'attributes' => [parent::class, 'attributes', null],
        'brand' => [parent::class, 'brand', null],
        'category' => [parent::class, 'category', null],
        'description' => [parent::class, 'description', null],
        'gallery' => [parent::class, 'gallery', null],
        'id' => [parent::class, 'id', null],
        'inStock' => [parent::class, 'inStock', null],
        'name' => [parent::class, 'name', null],
        'prices' => [parent::class, 'prices', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
